name: SOPS-Diff PR Integration

on:
  pull_request:
    paths:
      - '**.enc.yaml'
      - '**.enc.yml'
      - '**.enc.json'
      - '**.enc.env'

jobs:
  sops-diff:
    runs-on: ubuntu-latest
    # These permissions are needed to write PR comments
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This is important to get all the history for proper diffing
      
      - name: Install SOPS
        run: |
          wget https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64 -O /usr/local/bin/sops
          chmod +x /usr/local/bin/sops
      
      - name: Install sops-diff
        run: |
          curl -L https://github.com/saltydogtechnology/sops-diff/releases/download/v0.1.0/sops-diff-v0.1.0-linux-amd64.tar.gz | tar xz
          chmod +x sops-diff-linux-amd64
          mv sops-diff-linux-amd64 /usr/local/bin/sops-diff
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Get list of changed encrypted files
        id: get-files
        run: |
          # Get the base branch and head branch references
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"
          
          # Get list of modified encrypted files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E '\.enc\.(json|yaml|yml|env)$' || echo "")
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "No encrypted files changed in this PR."
            echo "changed_files=" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Save list of files and branch references for the next step
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          echo "base_branch=$BASE_BRANCH" >> $GITHUB_OUTPUT
          echo "head_branch=$HEAD_BRANCH" >> $GITHUB_OUTPUT
          
          echo "Changed encrypted files:"
          echo "$CHANGED_FILES"
      
      - name: Generate SOPS diffs
        id: generate-diffs
        if: steps.get-files.outputs.changed_files != ''
        run: |
          # Get data from previous step
          BASE_BRANCH="${{ steps.get-files.outputs.base_branch }}"
          HEAD_BRANCH="${{ steps.get-files.outputs.head_branch }}"
          CHANGED_FILES="${{ steps.get-files.outputs.changed_files }}"
          
          # Create a directory for the diff outputs
          mkdir -p /tmp/sops-diffs
          
          echo "::group::SOPS Encrypted File Diffs"
          for FILE in $CHANGED_FILES; do
            echo "Processing diff for $FILE"
            
            # Generate both a summary diff and a full diff using branch comparison
            DIFF_OUTPUT_FILE="/tmp/sops-diffs/${FILE//\//_}.diff"
            SUMMARY_OUTPUT_FILE="/tmp/sops-diffs/${FILE//\//_}.summary.diff"
            
            # Create full diff using branch comparison
            sops-diff --git origin/${BASE_BRANCH}:${FILE} origin/${HEAD_BRANCH}:${FILE} > "$DIFF_OUTPUT_FILE" 2>/dev/null
            
            # Create summary diff using branch comparison
            sops-diff --git --summary origin/${BASE_BRANCH}:${FILE} origin/${HEAD_BRANCH}:${FILE} > "$SUMMARY_OUTPUT_FILE" 2>/dev/null
            
            echo "Generated diff for $FILE"
          done
          echo "::endgroup::"
          
          # Prepare comment content
          echo 'COMMENT<<EOF' >> $GITHUB_ENV
          echo '### SOPS-Diff Report for Encrypted Files 🔒' >> $GITHUB_ENV
          echo '' >> $GITHUB_ENV
          echo 'The following encrypted files were modified in this PR:' >> $GITHUB_ENV
          echo '' >> $GITHUB_ENV
          
          for FILE in $CHANGED_FILES; do
            SUMMARY_OUTPUT_FILE="/tmp/sops-diffs/${FILE//\//_}.summary.diff"
            
            # Add file header
            echo "#### $FILE" >> $GITHUB_ENV
            echo '```diff' >> $GITHUB_ENV
            
            # Add summary content (keys only, safer for public viewing)
            if [ -f "$SUMMARY_OUTPUT_FILE" ] && [ -s "$SUMMARY_OUTPUT_FILE" ]; then
              cat "$SUMMARY_OUTPUT_FILE" >> $GITHUB_ENV
            else
              echo "No significant changes detected or error generating diff." >> $GITHUB_ENV
            fi
            echo '```' >> $GITHUB_ENV
            echo '' >> $GITHUB_ENV
          done
          
          echo 'For security reasons, only key changes are shown in this comment. Reviewers should check the actual values.' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      
      - name: Comment on PR
        if: steps.get-files.outputs.changed_files != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = process.env.COMMENT;
            if (comment && comment !== 'COMMENT') {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }