name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'
          check-latest: true

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run tests
        run: go test -v ./...

      - name: Set up release environment
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "RELEASE_VERSION_NUMBER=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build release binaries
        run: |
          mkdir -p bin
          # Linux
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.Version=${{ env.RELEASE_VERSION_NUMBER }}" -o bin/sops-diff-linux-amd64
          GOOS=linux GOARCH=arm64 go build -ldflags "-X main.Version=${{ env.RELEASE_VERSION_NUMBER }}" -o bin/sops-diff-linux-arm64
          
          # macOS
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.Version=${{ env.RELEASE_VERSION_NUMBER }}" -o bin/sops-diff-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.Version=${{ env.RELEASE_VERSION_NUMBER }}" -o bin/sops-diff-darwin-arm64
          
          # Windows
          GOOS=windows GOARCH=amd64 go build -ldflags "-X main.Version=${{ env.RELEASE_VERSION_NUMBER }}" -o bin/sops-diff-windows-amd64.exe
          GOOS=windows GOARCH=arm64 go build -ldflags "-X main.Version=${{ env.RELEASE_VERSION_NUMBER }}" -o bin/sops-diff-windows-arm64.exe

      - name: Create archives
        run: |
          mkdir -p artifacts
          
          # Linux archives
          tar -czf artifacts/sops-diff-${{ env.RELEASE_VERSION }}-linux-amd64.tar.gz -C bin sops-diff-linux-amd64
          tar -czf artifacts/sops-diff-${{ env.RELEASE_VERSION }}-linux-arm64.tar.gz -C bin sops-diff-linux-arm64
          
          # macOS archives
          tar -czf artifacts/sops-diff-${{ env.RELEASE_VERSION }}-darwin-amd64.tar.gz -C bin sops-diff-darwin-amd64
          tar -czf artifacts/sops-diff-${{ env.RELEASE_VERSION }}-darwin-arm64.tar.gz -C bin sops-diff-darwin-arm64
          
          # Windows archives
          cd bin
          zip ../artifacts/sops-diff-${{ env.RELEASE_VERSION }}-windows-amd64.zip sops-diff-windows-amd64.exe
          zip ../artifacts/sops-diff-${{ env.RELEASE_VERSION }}-windows-arm64.zip sops-diff-windows-arm64.exe
          cd ..
          
          # Generate checksums
          cd artifacts
          sha256sum * > sops-diff-${{ env.RELEASE_VERSION }}-checksums.txt
          cd ..

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: ".github/changelog-config.json"
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: SOPS-Diff ${{ env.RELEASE_VERSION }}
          body: |
            SOPS-Diff ${{ env.RELEASE_VERSION }}
            
            ${{ steps.changelog.outputs.changelog }}
            
            ## Installation
            
            ### Linux (amd64)
            ```
            curl -L https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_VERSION }}/sops-diff-${{ env.RELEASE_VERSION }}-linux-amd64.tar.gz | tar xz
            sudo mv sops-diff-linux-amd64 /usr/local/bin/sops-diff
            ```
            
            ### macOS (amd64)
            ```
            curl -L https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_VERSION }}/sops-diff-${{ env.RELEASE_VERSION }}-darwin-amd64.tar.gz | tar xz
            sudo mv sops-diff-darwin-amd64 /usr/local/bin/sops-diff
            ```
            
            ### macOS (Apple Silicon)
            ```
            curl -L https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_VERSION }}/sops-diff-${{ env.RELEASE_VERSION }}-darwin-arm64.tar.gz | tar xz
            sudo mv sops-diff-darwin-arm64 /usr/local/bin/sops-diff
            ```
            
            For Windows, download the appropriate zip file and extract the executable.
            
            See full installation and usage instructions in the [README](https://github.com/${{ github.repository }}/blob/main/README.md).
          files: |
            artifacts/*
          draft: false
          prerelease: false
          token: ${{ secrets.RELEASE_TOKEN }}

  # docker:
  #   runs-on: ubuntu-latest
  #   needs: goreleaser
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Set up environment
  #       run: |
  #         echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
  #         echo "RELEASE_VERSION_NUMBER=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         push: true
  #         tags: |
  #           ghcr.io/${{ github.repository }}:latest
  #           ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}
  #         build-args: |
  #           VERSION=${{ env.RELEASE_VERSION_NUMBER }}
  #         platforms: linux/amd64,linux/arm64
